Added packages to incorporate new barrel ECal based on SciGlass
sPHENIX-Collaboration/coresoftware pull request #1233
Opened 2021-07-02 18:29 UTC by nathalysns

[comment]: <> 
-  Add SciGlass as a new material.
-  Introduce new Calorimeter type based on sciglass for Barrel (BECAL).
- Adaptation of RawTowerBuilderByHitIndex to incorporate sciglass barrel geometry. Added new geometry description RawTowerGeomv4 with different angle definitions. 
- EventEvaluator adapted to read BECAL. 

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> 
-  Add SciGlass as a new material.
-  Introduce new Calorimeter type based on sciglass for Barrel (BECAL).
- Adaptation of RawTowerBuilderByHitIndex to incorporate sciglass barrel geometry. Added new geometry description RawTowerGeomv4 with different angle definitions. 
- EventEvaluator adapted to read BECAL.

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)

2021-07-02 18:35 UTC, blackcathj commented
> This is sPHENIX Jenkins CI. I can not test this pull request because I am only allowed to download pull requests from members of the GitHub [sPHENIX-collaboration](https://github.com/orgs/sPHENIX-Collaboration/people).
> 
> Are you a member of GitHub [sPHENIX-collaboration](https://github.com/orgs/sPHENIX-Collaboration/people)? If not, please contact Jin Huang or Chris Pinkenburg following the [sPHENIX software day-1 checklist](https://wiki.bnl.gov/sPHENIX/index.php/SPHENIX_software_day-1_checklist).

Starting manually at https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/sPHENIX_CoreSoftware_PullRequest/2612/

2021-07-02 22:31 UTC, blackcathj requested changes
Two suggestions made inline to help future maintenance and help group EIC BECal code together in `fun4all_eicdetectors/simulation/g4simulation/g4eiccalos/`

2021-07-02 22:31 UTC, blackcathj commented on simulation/g4simulation/g4main/PHG4Reco.cc
> +  G4Material *sciglass = new G4Material("sciglass", density = 4.22 * g / cm3, ncomponents = 4,  kStateSolid);
Please consider move this definition to part of the `PHG4BarrelEcalDetector.cc` . It would be also useful to make the material name unique and descriptive so in case different variety of Scintillation Glass is used in the future.

2021-07-02 22:31 UTC, blackcathj commented on simulation/g4simulation/g4calo/RawTowerBuilderByHitIndex.cc
> +  if (m_Detector == "BECAL"){
So much as been customized for the EIC BECAL through this if-switch, it would be useful to copy the original `RawTowerBuilderByHitIndex` to `fun4all_eicdetectors/simulation/g4simulation/g4eiccalos/` as a dedicated tower builder for BECAL. It also help future maintenance on BECAL by 1) not interfering tower maker with forward HCal by using its own tower builder 2) detach and independent from changing the sPHENIX codebases.

2021-07-05 18:38 UTC, nathalysns commented
Adjusted classes accordingly to the comments.

2021-07-06 20:32 UTC, merged