Implement global alignment constants
sPHENIX-Collaboration/coresoftware pull request #1642
Opened 2022-08-31 20:34 UTC by rboucher43

[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )
Adds alignment parameters to Acts local to global transformations, and takes alignment parameters from the database. Alignment parameters are currently all zero in the database. 

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)

2022-09-01 12:57 UTC, pinkenburg commented
Please follow the include file conventions in https://wiki.sphenix.bnl.gov/index.php/Codingconventions#Include_Files
Breaking them can lead to very hard (means impossible for even most expert users) to debug issues
Please remove -L$(ROOTSYS)/lib from the LIBADD, it is already in LDADD (where the -L flags belong)

2022-09-02 00:25 UTC, osbornjd requested changes
1. In general there is a lot of old code that is commented out - we should remove it completely to not confuse ourselves later (e.g. in ActsGeometry). 
2. A lot of the methods in ActsGeometry had their constness removed while trying to dig through an Acts compiler error about constness. But, if I recall, the compiler error didn't actually have to do with the constness in our class. If so, we should reimplement them. @adfrawley any comment on this, since I think (if I remember correctly) I talked to you about it?
3. We should also understand the drop in efficiency and pT resolution that Jenkins sees. It is probably related to the z position of the TPC clusters, as in the TPC QA the cluster z residuals look almost inverted.

Otherwise this looks like a great PR, I made a few other small comments but this is excellent to see!

2022-09-02 00:25 UTC, osbornjd commented on offline/packages/trackreco/PHActsTrkFitter.cc
> +	      double drift_velocity = 8.0e-3;  // cm/ns
We should obtain this from the globally settable variable in ActsGeometry

2022-09-02 02:23 UTC, sPHENIX-GitHub-l commented
Hi Joe,

I don't recall the part about constness not being the problem. If I recall correctly,  the problem we had was that we could not update the geometry context if the ActsTrackingGeometry class was const, since const classes cannot have non-const members. I had to remove the constness from all members to get things to compile. Possibly I misunderstood something.

You are correct about map2, that was overlooked when deleting some debugging code. I agree, I don't know how it compiled.
We will fix the ActsGeometry include.
Yes, sPHENIXActsDetectorElement::use_alignment is obsolete, we missed it.

The block of code in PHActsTrkFitter enabled by the test_transform flag was never intended to be left there permanently. But we will fix that, since we decided to keep that block there for a while.

Thanks for the useful comments!
Tony


________________________________
From: sPHENIX-GitHub-l ***@***.***> on behalf of Joe Osborn ***@***.***>
Sent: Thursday, September 1, 2022 8:26 PM
To: sPHENIX-Collaboration/coresoftware ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [Sphenix-github-l] [sPHENIX-Collaboration/coresoftware] Implement global alignment constants (PR #1642)


@osbornjd requested changes on this pull request.

  1.  In general there is a lot of old code that is commented out - we should remove it completely to not confuse ourselves later (e.g. in ActsGeometry).
  2.  A lot of the methods in ActsGeometry had their constness removed while trying to dig through an Acts compiler error about constness. But, if I recall, the compiler error didn't actually have to do with the constness in our class. If so, we should reimplement them. @adfrawley<https://urldefense.com/v3/__https://github.com/adfrawley__;!!PhOWcWs!1LlGPMPqXJspA2PCpm7IO75vjyM8osWngrLlQEuLPHpvUkb-OuRq6dfUa4y6LLc-WGS_70dOUwh3ZI8YKM2_EOd3$> any comment on this, since I think (if I remember correctly) I talked to you about it?

Otherwise this looks like a great PR, I made a few other small comments but this is excellent to see!

________________________________

In offline/packages/trackbase/AlignmentTransformation.cc<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1642*discussion_r961050103__;Iw!!PhOWcWs!1LlGPMPqXJspA2PCpm7IO75vjyM8osWngrLlQEuLPHpvUkb-OuRq6dfUa4y6LLc-WGS_70dOUwh3ZI8YKHwx3fOg$>:

> +      transformMap->addTransform(id,transform);
+      }
+     else
+       {
+        std::cout<< "Error: Invalid Hitsetkey" << std::endl;
+       }
+     if(localVerbosity)
+       {
+        std::cout << i << " " <<hitsetkey << " " <<alpha<< " " <<beta<< " " <<gamma<< " " <<dx<< " " <<dy<< " " <<dz << std::endl;
+       }
+   }
+
+ const auto map = transformMap->getMap();
+ Acts::GeometryContext context(map);
+
+ const auto map2 = context.get<std::map<Acts::GeometryIdentifier, Acts::Transform3>>();


As far as I can tell, this isn't used, right? This should throw a compiler error that Jenkins finds.

________________________________

In offline/packages/trackbase/sPHENIXActsDetectorElement.cc<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1642*discussion_r961053265__;Iw!!PhOWcWs!1LlGPMPqXJspA2PCpm7IO75vjyM8osWngrLlQEuLPHpvUkb-OuRq6dfUa4y6LLc-WGS_70dOUwh3ZI8YKFvnD4_6$>:

>
+#include <ActsGeometry.h>


This should be with quotes "" instead of brackets <> since ActsGeometry is in the same directory (trackbase) and we want to use whatever the version is in that directory, not whatever is in the offline build.

________________________________

In offline/packages/trackbase/sPHENIXActsDetectorElement.cc<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1642*discussion_r961053718__;Iw!!PhOWcWs!1LlGPMPqXJspA2PCpm7IO75vjyM8osWngrLlQEuLPHpvUkb-OuRq6dfUa4y6LLc-WGS_70dOUwh3ZI8YKMPSUfCn$>:

>
 sPHENIXActsDetectorElement::~sPHENIXActsDetectorElement() = default;
+
+bool sPHENIXActsDetectorElement::use_alignment = false;


Is this used anymore? I thought we discussed having the boolean at the container level (which it appears to be). Assuming not, we should remove it

________________________________

In offline/packages/trackreco/PHActsTrkFitter.cc<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1642*discussion_r961194874__;Iw!!PhOWcWs!1LlGPMPqXJspA2PCpm7IO75vjyM8osWngrLlQEuLPHpvUkb-OuRq6dfUa4y6LLc-WGS_70dOUwh3ZI8YKDKAWwTD$>:

> +      if(test_transforms)
+       {
+
+         // Alignment transformation testing purposes
+         auto hitsetkey = TrkrDefs::getHitSetKeyFromClusKey(key);
+
+         float globphi = atan2(global(1),global(0))*180.0/M_PI;
+         std::cout << "Check in TrkFitter: global phi " << globphi << " hitsetkey: " << hitsetkey <<" global: " << std::endl << global << std::endl;
+
+         auto x = cluster->getLocalX() * 10.0;   // mm
+         auto y = cluster->getLocalY() * 10.0;
+
+         if(trkrid == TrkrDefs::tpcId)
+           {
+             // must convert local Y from cluster average time of arival to local cluster z position
+             double drift_velocity = 8.0e-3;  // cm/ns


We should obtain this from the globally settable variable in ActsGeometry

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1642*pullrequestreview-1093981526__;Iw!!PhOWcWs!1LlGPMPqXJspA2PCpm7IO75vjyM8osWngrLlQEuLPHpvUkb-OuRq6dfUa4y6LLc-WGS_70dOUwh3ZI8YKPihfFt5$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AEALMH42MTL2R75QFKGMPBLV4FCSFANCNFSM6AAAAAAQBXCGKA__;!!PhOWcWs!1LlGPMPqXJspA2PCpm7IO75vjyM8osWngrLlQEuLPHpvUkb-OuRq6dfUa4y6LLc-WGS_70dOUwh3ZI8YKCne3RNH$>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2022-09-02 02:34 UTC, osbornjd commented
Okay, I couldn't remember on the const issue. That's fine then, I just needed a refresher. 

My guess is once the TPC z cluster residual issue gets understood it will fix the issues at the track level.

2022-09-03 00:45 UTC, adfrawley commented
I do not see any reported issues that are related to this PR.

Tony
________________________________
From: sphenix-jenkins-ci[bot] ***@***.***>
Sent: Friday, September 2, 2022 7:26 PM
To: sPHENIX-Collaboration/coresoftware ***@***.***>
Cc: Anthony Frawley ***@***.***>; Mention ***@***.***>
Subject: Re: [sPHENIX-Collaboration/coresoftware] Implement global alignment constants (PR #1642)


Build & test report

Report for commit e02649f756c2a8688916f93a1c60ae2c69064949<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1642/commits/e02649f756c2a8688916f93a1c60ae2c69064949__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp70VTv_K$>:
[Jenkins on fire]<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/sPHENIX_CoreSoftware_PullRequest/3915/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEpy79yplE$>

  *   [Build Status] <https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/sPHENIX_CoreSoftware_PullRequest/3915/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEpy79yplE$>  builds and tests overall are FAILURE<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/sPHENIX_CoreSoftware_PullRequest/3915/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEpy79yplE$>.
  *   [Build Status] <https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Clang/3335/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp85vzdkI$>  Build with configuration of gcc-8.3 / clang is SUCCESS<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Clang/3335/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp85vzdkI$>, 📊clang report (full)<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Clang/3335/*clang/__;Lw!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp99pnJFe$>/(new)<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Clang/3335/*clang/new/__;Lw!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp68b-BHU$>, build log<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Clang/3335/*artifact/build/clang/rebuild.log__;Lw!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp_OsNJod$>
  *   [Build Status] <https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Master-gcc8/2798/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp4AuwP_1$>  Build with configuration of gcc-8.3 / new is FAILURE<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Master-gcc8/2798/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp4AuwP_1$>, 📊Compiler report (full)<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Master-gcc8/2798/*gcc/__;Lw!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp70E0zu8$>/(new)<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Master-gcc8/2798/*gcc/new/__;Lw!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEpySpKSVN$>, build log<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Master-gcc8/2798/*artifact/build/new/rebuild.log__;Lw!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEpw5Ykyuk$>
     *   [Build Status] <https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-DST-readback/4948/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp5aTVFIP$>  Generating DST and readback: build is SUCCESS<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-DST-readback/4948/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp5aTVFIP$>
     *   [Build Status] <https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-calo-single-qa/3533/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp3g0pZg9$>  Calorimeter QA: build is SUCCESS<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-calo-single-qa/3533/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp3g0pZg9$>
        *   📊 QA-calorimeter for e- at p_T=4GeV<https://urldefense.com/v3/__https://nbviewer.jupyter.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-calo-single-qa-3533-e-_pT4_Sum8/QA-calorimeter.ipynb__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp85lhwuA$> : combined Chi2/nDoF = 68.7852 / 72, and combined p-Value = 0.58558
        *   📊 QA-calorimeter for pi+ at p_T=30GeV<https://urldefense.com/v3/__https://nbviewer.jupyter.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-calo-single-qa-3533-pi*_pT30_Sum8/QA-calorimeter.ipynb__;Kw!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp_rUs4VB$> : combined Chi2/nDoF = 1059.15 / 72, and combined p-Value = 2.29928e-175
        *   📊 QA-calorimetric-jet for e- at p_T=4GeV<https://urldefense.com/v3/__https://nbviewer.jupyter.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-calo-single-qa-3533-e-_pT4_Sum8/QA-calorimetric-jet.ipynb__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp1NGC9i0$> : combined Chi2/nDoF = 3.32843 / 42, and combined p-Value = 1
        *   📊 QA-calorimetric-jet for pi+ at p_T=30GeV<https://urldefense.com/v3/__https://nbviewer.jupyter.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-calo-single-qa-3533-pi*_pT30_Sum8/QA-calorimetric-jet.ipynb__;Kw!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEpyZvzVWv$> : combined Chi2/nDoF = 161.698 / 42, and combined p-Value = 5.97412e-16
     *   [Build Status] <https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-tracking-high-occupancy-qa/2301/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEpzL0cBHu$>  Tracking QA at high occupancy: build is SUCCESS<https://urldefense.com/v3/__https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-tracking-high-occupancy-qa/2301/__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEpzL0cBHu$>
        *   📊 QA-Intt<https://urldefense.com/v3/__https://nbviewer.jupyter.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-tracking-high-occupancy-qa-2301-test-tracking_Event50_Sum10/QA-Intt.ipynb__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp5iUU5c3$> : combined Chi2/nDoF = 18.2525 / 72, and combined p-Value = 1
        *   📊 QA-Micromegas<https://urldefense.com/v3/__https://nbviewer.jupyter.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-tracking-high-occupancy-qa-2301-test-tracking_Event50_Sum10/QA-Micromegas.ipynb__;!!PhOWcWs!23SUhOwXrJYLwi0KY3MmICSALiln-3kn0gl3ijzo_zSTfLr3twq3xnuvm0_t5oS8b2vmNDl8VPNU6DmEp7dictal$> : combined Chi2/nDoF = 15.8015 / 20, and combined p-Value = 0.72886
        *   📊 QA-Mvtx<https://urldefense.com/v3/__https://nbviewer.jupyter.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-tracking-high-occupancy-qa-2301-tes [...]

2022-09-03 01:33 UTC, osbornjd commented
Are the changes in the TPC cluster residuals understood? That (I suspect) negatively impacts the tracking and vertexing QA, especially in the z direction.

2022-09-04 15:29 UTC, osbornjd commented
Looks good to me, @pinkenburg I assume the overlap failures are from the ongoing hcal issue so I will go ahead and merge this.

2022-09-04 15:29 UTC, merged