Proper EvtGen Integration to GEANT Simulation (No QA Module Yet)
sPHENIX-Collaboration/coresoftware pull request #1681
Opened 2022-09-26 13:19 UTC by MYOMAO

This is another fresh pull request based on the previous pull request work-in-progress attempt for the implementation of EvtGen to the sPHENIX software:

https://github.com/sPHENIX-Collaboration/coresoftware/pull/1618

We have cleaned up everything to comply to the sPHENIX coding standard.

For this pull request, we have properly implemented the EvtGen decayer with proper link to the particle basic properties and decay channels inputs directly from the latest EvtGen software. In addition, we also make the particle cascade explicit to have all intermediate vertices. The GEANT undefined particles will be decayed immediately until becoming defined and pass to the GEANT to propagate its vertex.

Currently, with this update, in the default setting, the heavy flavor particles will decay by the EvtGen decayer until reaching to light flavor particle, which will be handle by GEANT Internal Decayer.

The options in terms of enum for decayers is defined as follows:

0 - GEANT Internal Decayer
1 - PYTHIA 6 Decayer
2- EvtGen Decayer 

User can customize their decay based on their preference. 
 
It should also be mention that we also have the QA codes to make sure the EvtGen decay make sense before passing to GEANT 4. We also have a quick glance at the PHG4TruthInfoContainer at SvtxEvaluator.cc and appears to look good. A comprehensive QA module with both before and after passing to GEANT 4 is in development. 

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)

2022-09-27 14:42 UTC, blackcathj requested changes
There are major problems and require clean up git history and some rewrite/clean up. Also please add QA module to proof the final code works

2022-09-27 14:42 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  mVertex = new EvtVector4R(0, 0, 0, 0);
Vertex is new-ed at every decay and no clean up? And how is the vertex used?

2022-09-27 14:42 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +				std::cout << "Process Done, Skip" << std::endl;
Unsuppressed std::cout

2022-09-27 14:42 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +int G4EvtGenDecayer::ImportParticles(std::vector<int>& DecayPDGID, std::vector<int>& DecayStatus, std::vector<G4LorentzVector>& DecayMom, std::vector<G4LorentzVector>& DecayVtx)
The logic here is too convoluted, like patch on patch. Completely rewrite this part to merge this function with `ImportDecayProducts`

2022-09-27 14:42 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  mParticle = EvtParticleFactory::particleFactory(parentID, p_init);
Make sure there is no memory leak with `mParticle`

2022-09-27 14:42 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +void G4EvtGenDecayer::SetVertex(G4LorentzVector* r)
Who use this function and why it is here?

2022-09-27 14:42 UTC, blackcathj commented on simulation/g4simulation/g4main/PHG4Reco.cc
> +#if G4VERSION_NUMBER >= 1033
git history has problem. This is undoing a bug fix to PHG4Reco introduced earlier!

2022-09-27 14:42 UTC, blackcathj commented on simulation/g4simulation/g4main/PHG4Reco.cc
> +  for (SubsysReco *reco : m_SubsystemList)
Don't change lines that irrelevant to your work

2022-09-27 14:42 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +	  decayProducts->PushProducts(dynamicParticle);
Add logic check that this particle has the same vertex as the parent particle from EvtGen

2022-09-27 15:24 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +int G4EvtGenDecayer::ImportParticles(std::vector<int>& DecayPDGID, std::vector<int>& DecayStatus, std::vector<G4LorentzVector>& DecayMom, std::vector<G4LorentzVector>& DecayVtx)
Ok I will implement.

2022-09-28 15:05 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +int G4EvtGenDecayer::ImportParticles(std::vector<int>& DecayPDGID, std::vector<int>& DecayStatus, std::vector<G4LorentzVector>& DecayMom, std::vector<G4LorentzVector>& DecayVtx)
Merged the function ImportProduct() to the code ImportDecayProducts()

2022-09-28 15:09 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +void G4EvtGenDecayer::SetVertex(G4LorentzVector* r)
Indeed this function is not used. I have remove it.

2022-09-28 15:10 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +	  decayProducts->PushProducts(dynamicParticle);
Logic check added.

2022-09-28 15:11 UTC, MYOMAO commented on simulation/g4simulation/g4main/PHG4Reco.cc
> +#if G4VERSION_NUMBER >= 1033
OK. Again fix it by modifying the latest PHG4Reco.cc version.

2022-10-04 10:54 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  mVertex = new EvtVector4R(0, 0, 0, 0);
This part is now removed. We check the vertices and they make sense now.

2022-10-04 10:56 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  mParticle = EvtParticleFactory::particleFactory(parentID, p_init);
I run the following command to use Valgrind:

valgrind -v --num-callers=30 --error-limit=no --suppressions=/opt/sphenix/core/root/root.supp --leak-check=full --leak-resolution=high --tool=memcheck --log-file=valgrinderrors.log --gen-suppressions=all root -b -l -q Fun4All_G4_sPHENIX.C'(1)'

The following is my valgrind report:

[zshi@rcas6008 sPHENIX]$ grep -A10 "LEAK SUMMARY" valgrinderrors.log

==19264== LEAK SUMMARY:
==19264==    definitely lost: 0 bytes in 0 blocks
==19264==    indirectly lost: 0 bytes in 0 blocks
==19264==      possibly lost: 0 bytes in 0 blocks
==19264==    still reachable: 75 bytes in 1 blocks
==19264==         suppressed: 0 bytes in 0 blocks
==19264== Reachable blocks (those to which a pointer was found) are not shown.
==19264== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==19264== 
==19264== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
[zshi@rcas6008 sPHENIX]$ 


So in conclusion, no memory leak is detected so far for my codes

2022-10-07 01:50 UTC, blackcathj requested changes
Improvements. But still, quite some work remain TODO

2022-10-07 01:50 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  eng = new EvtSimpleRandomEngine();
Any random number need to be seeded with 
```c++
unsigned int seed = PHRandomSeed();  // fixed seed is handled in this funtcion
```
as in https://github.com/sPHENIX-Collaboration/coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxDigitizer.cc#L37

2022-10-07 01:50 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +G4DecayProducts* G4EvtGenDecayer::ImportDecayProducts(const G4Track& track)
`clang-format` this code

2022-10-07 01:50 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  G4LorentzVector* ParMom = new G4LorentzVector;
Use `unique_ptr` instead, similar to a few other pointers that your code owns
https://cplusplus.com/reference/memory/unique_ptr/

2022-10-07 01:50 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  mParticle->setDiagonalSpinDensity();
Find out spin density from G4

2022-10-07 01:50 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +void G4EvtGenDecayer::Decay(int pdgId, G4LorentzVector* _p)
Merge this function to the main function

2022-10-07 01:50 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +void G4EvtGenDecayer::AppendParticle(int pdg, G4LorentzVector* _p)
Merge this function to the main function

2022-10-07 01:50 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +	for (auto vtx: evt->vertices()) {
The next 200 lines are way too complicated than necessary. Rewrite this with single navigation loop through the tree

2022-10-08 02:36 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  G4LorentzVector* ParMom = new G4LorentzVector;
Converted ParMom to pointer.

2022-10-08 02:36 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  eng = new EvtSimpleRandomEngine();
No idea how to match EvtRandomEngine*  to unsigned int? Any suggestions?

2022-10-08 02:37 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +void G4EvtGenDecayer::Decay(int pdgId, G4LorentzVector* _p)
Adopted!

2022-10-08 02:37 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +void G4EvtGenDecayer::AppendParticle(int pdg, G4LorentzVector* _p)
Adopted!

2022-10-08 02:47 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  mParticle->setDiagonalSpinDensity();
It is actually from EvtGen codes. Since for now we do care about spin, can we just ignore the spin by commenting it our?

2022-10-19 05:41 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  eng = new EvtSimpleRandomEngine();
It is now implemented in the files PHEvtGenRandomEngine.cc and PHEvtGenRandomEngine.hh and used in:

https://github.com/MYOMAO/coresoftware/blob/master/simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc#L72

2022-10-19 05:42 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +G4DecayProducts* G4EvtGenDecayer::ImportDecayProducts(const G4Track& track)
DONE

2022-10-19 05:42 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  mParticle->setDiagonalSpinDensity();
Will finish it later for now

2022-10-19 05:43 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +	for (auto vtx: evt->vertices()) {
Implement BFS algorithm with queue to simplify this loop.

2022-10-20 18:21 UTC, blackcathj requested changes
The code still crashes. Check the valgrind output later at https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-valgrind-pipeline/2151/

2022-10-20 18:21 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +    IsG4Detectable(int ParPDGID, G4bool warn) const
GetParticleDefinition and IsG4Detectable are duplicated code. Keep one.

2022-10-20 18:21 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  std::unique_ptr<G4LorentzVector> ParMom(new G4LorentzVector);
Where was `ParMom` used?

2022-10-20 18:21 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  auto mParticle = EvtParticleFactory::particleFactory(parentID, p_init);
Do you own the object behind `mParticle` and do you need to clean it up?

2022-10-20 18:21 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  p[0] = momentum.x() / GeV;
Double check units expected by `EvtGen`

2022-10-20 18:21 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  std::queue<int> stack;
A queue named stack?

2022-10-20 18:21 UTC, blackcathj commented on simulation/g4simulation/g4decayer/PHEvtGenRandomEngine.cc
> +  m_RandomGenerator = gsl_rng_alloc(gsl_rng_mt19937);
where did you delete `m_RandomGenerator`?

2022-10-21 23:39 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/PHEvtGenRandomEngine.cc
> +  m_RandomGenerator = gsl_rng_alloc(gsl_rng_mt19937);
Now will do!

2022-10-25 02:39 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +  std::unique_ptr<G4LorentzVector> ParMom(new G4LorentzVector);
Removed

2022-10-25 04:19 UTC, blackcathj requested changes
Much improved. Still clean up needed: 

* Figure out how to fix these problems: 
```
EvtGen:Warning in EvtPythiaEngine. Trying to redefine Pythia table for Xi_c0 for a decay channel that has no daughters. Keeping Pythia default (if available).
EvtGen:Warning in EvtPythiaEngine. Trying to redefine Pythia table for Omega_c0 for a decay channel that has no daughters. Keeping Pythia default (if available).
EvtGen:Warning in EvtPythiaEngine. Trying to redefine Pythia table for Xi_c+ for a decay channel that has no daughters. Keeping Pythia default (if available).
 PYTHIA Warning in HadronWidths::check: inconsistent lower mass bound 113
 PYTHIA Warning in HadronWidths::check: inconsistent upper mass bound 113
 PYTHIA Warning in HadronWidths::check: inconsistent lower mass bound 113
 PYTHIA Warning in HadronWidths::check: inconsistent upper mass bound 113
 PYTHIA Warning in TauDecays::decay: unknown uncorrelated tau production, assuming unpolarized  
 PYTHIA Error in HadronWidths::pickDecay: no channels have positive widths for 313 @ 1.208720 GeV
/var/lib/jenkins/workspace/sPHENIX/Build-Master-gcc8@2/coresoftware/simulation/g4simulation/g4eval/SvtxTruthEval.cc:1162:    **** Oops! No valid solution for tup or tdn, tdn = -168.804 tup = -0.000
   radius 67.134 rbegin 67.134 rend 67.929
   x0 67.081 x1 67.874
   y0 -2.684 y1 -2.735
   z0 56.999 z1 57.606
   A 0.632 B 106.737 C 0.000
```
as in    https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-pipeline/4930/artifact/macros/detectors/sPHENIX/Fun4All_G4_sPHENIX.log by running this macro: https://github.com/sPHENIX-Collaboration/macros/pull/563/files 


* one time memory leaks, if possible to fix: 
  - https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-valgrind-pipeline/2168/valgrindResult/pid=49268,0x1a5743/
  - https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-valgrind-pipeline/2168/valgrindResult/pid=49268,0x1a389d/
  - https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-valgrind-pipeline/2168/valgrindResult/pid=49268,0x1a386e/

* Clean up unused comments, then `clang-format` your code

2022-10-25 04:19 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +IsG4Detectable(int ParPDGID, G4bool warn) const
Still, much duplicated `GetParticleDefinition()` and `IsG4Detectable()`

2022-10-25 04:19 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +	CLHEP::HepLorentzVector p;
Double check EvtGen expect GeV as units

2022-10-25 04:19 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +	EvtVector4R p_init(p[3],p[0],p[1],p[2]);
What is the point of `p` if it is converted to `p_init` immediately?

2022-10-25 04:19 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +	std::vector<int> CheckWhat;
What is purpose of this variable?

2022-10-25 04:19 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +			stack.push(part);
There is a way to grab the root particle without using an extra `for` loop then a `while` loop.

Remove these two loops and directly access the root particle and enter it to the stack. Double check the ROOT particle has the same PID as `pdgEncoding`

2022-10-25 04:19 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +					stack.push(children);
Change this to only `stack.push(children);` if not `Detectable`

2022-10-25 04:19 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +						if (dynamicParticle)
Add logic check if `dynamicParticle` is not valid

2022-10-25 04:19 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +							if(!SameVtxPos){
Add print out which particle and which vertex is causing this error

2022-10-26 19:22 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +					stack.push(children);
So here the logic is to push all particles regardless of Detectable or not. But then I will pop the particles that are Detectable. Probably this is equivalent to push all not Detectable particles?

2022-10-27 13:27 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +	EvtVector4R p_init(p[3],p[0],p[1],p[2]);
Remove p and directly construct p_init with px, py, pz, and E in GeV unit.

2022-10-27 13:29 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +							if(!SameVtxPos){
DONE!

2022-10-27 13:39 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +						if (dynamicParticle)
Yes, use `exit(1)`

2022-10-28 20:22 UTC, blackcathj commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +          if (!SameVtxPos)
Move this part to after line 157: there is no need for a long wait before making a warning which make the code look more complex than needed.

2022-11-01 17:44 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +	std::vector<int> CheckWhat;
It is a debug process and we have removed it in the new version of the codes

2022-11-01 17:44 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +			stack.push(part);
Adopted in the new version

2022-11-15 17:01 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +	for (auto vtx: evt->vertices()) {
Now implemented with Depth First Search Scheme using stack. It is also validated by the QA module.

2022-12-01 01:10 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +          if (!SameVtxPos)
Implemented depth first search using stack. Proven the codes work with QA modules in presentations.

2022-12-01 01:11 UTC, MYOMAO commented
> Much improved. Still clean up needed:
> 
> * Figure out how to fix these problems:
> 
> ```
> EvtGen:Warning in EvtPythiaEngine. Trying to redefine Pythia table for Xi_c0 for a decay channel that has no daughters. Keeping Pythia default (if available).
> EvtGen:Warning in EvtPythiaEngine. Trying to redefine Pythia table for Omega_c0 for a decay channel that has no daughters. Keeping Pythia default (if available).
> EvtGen:Warning in EvtPythiaEngine. Trying to redefine Pythia table for Xi_c+ for a decay channel that has no daughters. Keeping Pythia default (if available).
>  PYTHIA Warning in HadronWidths::check: inconsistent lower mass bound 113
>  PYTHIA Warning in HadronWidths::check: inconsistent upper mass bound 113
>  PYTHIA Warning in HadronWidths::check: inconsistent lower mass bound 113
>  PYTHIA Warning in HadronWidths::check: inconsistent upper mass bound 113
>  PYTHIA Warning in TauDecays::decay: unknown uncorrelated tau production, assuming unpolarized  
>  PYTHIA Error in HadronWidths::pickDecay: no channels have positive widths for 313 @ 1.208720 GeV
> /var/lib/jenkins/workspace/sPHENIX/Build-Master-gcc8@2/coresoftware/simulation/g4simulation/g4eval/SvtxTruthEval.cc:1162:    **** Oops! No valid solution for tup or tdn, tdn = -168.804 tup = -0.000
>    radius 67.134 rbegin 67.134 rend 67.929
>    x0 67.081 x1 67.874
>    y0 -2.684 y1 -2.735
>    z0 56.999 z1 57.606
>    A 0.632 B 106.737 C 0.000
> ```
> 
> as in https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-pipeline/4930/artifact/macros/detectors/sPHENIX/Fun4All_G4_sPHENIX.log by running this macro: https://github.com/sPHENIX-Collaboration/macros/pull/563/files
> 
> * one time memory leaks, if possible to fix:
>   
>   * https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-valgrind-pipeline/2168/valgrindResult/pid=49268,0x1a5743/
>   * https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-valgrind-pipeline/2168/valgrindResult/pid=49268,0x1a389d/
>   * https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-valgrind-pipeline/2168/valgrindResult/pid=49268,0x1a386e/
> * Clean up unused comments, then `clang-format` your code

New clean up version has been updated as a new commit.

2022-12-01 01:12 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +						if (dynamicParticle)
Adopted!

2022-12-01 01:13 UTC, MYOMAO commented on simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
> +	CLHEP::HepLorentzVector p;
Confirm in GeV units in QA

2023-01-11 19:16 UTC, closed without merging