Adding inital files
sPHENIX-Collaboration/coresoftware pull request #1740
Opened 2022-11-09 16:50 UTC by antoniocosilva

[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

Including files for jet tagging in the folder offline/packages/JetTagging.

## TODOs (if applicable)

- Change JET::SRC in some jet constituents
- Replace barcode by GEANT code

2022-11-18 15:42 UTC, osbornjd requested changes
Thanks again for submitting this PR, it is really useful and will greatly benefit the sPHENIX reconstruction. I have a few small comments and then a general design comment that we should discuss on what timeline it is implemented. Right now there is a lot of functionality in this one module - there is reconstructed and truth jet tagging, as well as creation of an output tree and some diagnostic histograms. I think we should separate this into 3 modules for the benefit of the longer term implementation in the reconstruction. Others can comment, but I suggest having : 
1. A reconstruction module that creates reconstructed HF resonance jets
2. A module that creates truth HF resonance jets
3. An analysis module that then creates the output tree/histograms for further user analysis

This would then be analogous to the current jet reconstruction [here](https://github.com/sPHENIX-Collaboration/macros/blob/26f35676a51be851ca9fd0d1aa537cfa7851a7da/common/G4_Jets.C#L40-L69) and would allow us to have a single module that is ready to run over reconstructed data as soon as we have it. We could make this two separate modules, e.g. `TruthHFResonanceJetTagger` and `RecoHFResonanceJetTagger`, or you could imagine having a module that takes as input the type of collection e.g. truth particles or reconstructed particle flow objects and looks up the appropriate container and builds the jets like
```
HFResonanceJetTagger *truth = new HFResonanceJetTagger("D0TruthJets");
truth->setInput("PHG4TruthInfo");
truth->setResonance("D0");
truth->setAlgorithm(antikt);
etc etc etc

HFResonanceJetTagger *reco = new HFResonanceJetTagger("D0RecoJets");
reco->setInput("ParticleFlowElements");
reco->setResonance("D0");
reco->setAlgorithm(antikt);
etc etc etc
```

2022-11-21 15:06 UTC, cdean-github commented on offline/packages/JetTagging/JetTagging.cc
> +  if (std::abs(track->get_px() - particle->Px()) < 0.00001 && std::abs(track->get_py() - particle->Py()) < 0.00001 && std::abs(track->get_pz() - particle->Pz()) < 0.00001)
KFParticle is supposed to save the track ID from the TrackMap [here](https://github.com/sPHENIX-Collaboration/coresoftware/blob/master/offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc#L163) but it didn't seem to be working for some reason. I looked at the code a while ago and couldn't see a reason for this. Also, a test of KFParticle last week did seem to have the track IDs saved. Let me take another look
```
---------------KFParticle candidate information---------------
Mother information:
Track ID: -1
PDG ID: 421, charge: 0, mass: 2.06553 GeV
(px,py,pz) = (-3.68652 +/- 0.0308201, -7.91933 +/- 0.0874316, 3.63364 +/- 0.0423492) GeV
(x,y,z) = (0.000414679 +/- 0.00155138, -0.018587 +/- 0.00290231, -3.5172 +/- 0.0016556) cm

Final track information:
Track ID: 0
PDG ID: -321, charge: -1, mass: 0 GeV
(px,py,pz) = (-1.4961 +/- 0.00839175, -1.57411 +/- 0.00892421, 0.542018 +/- 0.00327846) GeV
(x,y,z) = (0.00956997 +/- 0.000909375, -0.00903886 +/- 0.000872041, -3.52068 +/- 0.00193571) cm

Track ID: 4
PDG ID: 211, charge: 1, mass: 0 GeV
(px,py,pz) = (-2.19059 +/- 0.0300371, -6.34578 +/- 0.0885953, 3.09188 +/- 0.0431354) GeV
(x,y,z) = (0.00463916 +/- 0.000755806, -0.00629922 +/- 0.000496893, -3.52311 +/- 0.00100415) cm
```

2022-11-21 16:53 UTC, cdean-github commented on offline/packages/JetTagging/JetTagging.cc
> +  if (std::abs(track->get_px() - particle->Px()) < 0.00001 && std::abs(track->get_py() - particle->Py()) < 0.00001 && std::abs(track->get_pz() - particle->Pz()) < 0.00001)
Agh, found the bug. I was resetting the Id's. 
```
KFParticle* KFParticle_Container::insert(const KFParticle* particle)
{
  unsigned int index = 0;
  if (!m_kfpmap.empty()) index = m_kfpmap.rbegin()->first + 1;
  m_kfpmap.insert(std::make_pair(index, dynamic_cast<KFParticle*>(particle->Clone())));
  m_kfpmap[index]->SetId(index);
  return m_kfpmap[index];
}
```

2022-11-28 19:34 UTC, antoniocosilva commented on offline/packages/JetTagging/JetTagging.cc
> +void JetTagging::resetTreeVariables()
I removed the TTree from the module. I'm creating another module that reads the tagged jets from the node and make the TTree, there I'm replacing the -9999. by NAN.

2022-11-28 19:35 UTC, antoniocosilva commented on offline/packages/JetTagging/JetTagging.h
> +  Fun4AllHistoManager *m_hm;
It does not, I removed it. Thanks!

2022-11-28 19:37 UTC, antoniocosilva commented on offline/packages/JetTagging/JetTagging.cc
> +    createJetNode(topNode);
I changed it to always save the node. In the current state of the code it will always save the reconstructed level jets and, if the flag m_ismc is true, it will save also the truth level jets. Do you think this is fine? Or do you foresee a case where we would like to save the truth level but not the reconstructed?

2022-11-28 19:39 UTC, antoniocosilva commented on offline/packages/JetTagging/JetTagging.cc
> +  m_eventcount_h = new TH1I("eventcount_h", "Event Count", 2, -0.5, 1.5);
I fully agree! I removed the TTree and all the histograms from the module. I'm preparing another module to make a TTree getting the information from the node.

2022-11-28 19:40 UTC, antoniocosilva commented on offline/packages/JetTagging/JetTagging.cc
> +    TagCand = kfContainer->get(i);
Indeed. Now I'm checking if kfContainer exists.

2022-11-28 19:41 UTC, antoniocosilva commented on offline/packages/JetTagging/JetTagging.cc
> +  fastjet::JetDefinition *jetdef = new fastjet::JetDefinition(m_jetalgo, m_jetr, m_recomb_scheme, fastjet::Best);
Thanks! I'm now using std::unique_pointer

2022-11-28 19:41 UTC, antoniocosilva commented on offline/packages/JetTagging/JetTagging.cc
> +  ParticleFlowElementContainer *pflowContainer = findNode::getClass<ParticleFlowElementContainer>(topNode, "ParticleFlowElements");
I'm checking if the container exists now.

2022-11-28 19:42 UTC, antoniocosilva commented on offline/packages/JetTagging/JetTagging.h
> +#ifndef JETTAGGING_H__
I changed the name of the module to ResonanceJetTagging.

2022-11-28 19:43 UTC, osbornjd commented on offline/packages/JetTagging/JetTagging.cc
> +    createJetNode(topNode);
It could potentially be useful, for example if someone just wanted to run a set of D0 PYTHIA simulations and study the truth distributions. I imagine in most cases you would want both (or just the reconstructed) but if it is straightforward to do I would also add the truth jets. You could add a check for the corresponding nodes to build the new jet node. For example, if the reconstructed PF objects are available on the node tree, then build the reconstructed tagged jets. If the truth particles are available on the node tree, then build the truth tagged jets.

2022-11-28 19:49 UTC, antoniocosilva commented on offline/packages/JetTagging/JetTagging.cc
> +    createJetNode(topNode);
I see. I will work on that.

2022-12-08 14:18 UTC, osbornjd reviewed
Thanks Antonio, this is much improved and the separation between the analysis tree and the creation of the tagged jets is much better now. I only left one minor comment, and then there is just one other comment I have before we can merge this. Typically we would put the analysis tree class into the `analysis` repository, which everyone can use to store analysis code. `coresoftware` is generally reserved for the code that makes analysis level objects, e.g. `ResonanceJetTagging`. I would suggest moving `BuildResonanceJetTaggingTree` to a directory in the `analysis` repo [here](https://github.com/sphenix-collaboration/analysis) which is writeable for all sPHENIX members, no PR needed. Then we should be able to merge this

2022-12-08 14:18 UTC, osbornjd commented on offline/packages/ResonanceJetTagging/BuildResonanceJetTaggingTree.cc
> +    for (JetMapv1::Iter iter = m_taggedJetMap->begin(); iter != m_taggedJetMap->end(); ++iter)
We should have this be `JetMap::Iter iter` or `auto iter` instead of `JetMapv1::Iter iter`. The reason is that, in the event that we ever change to a `JetMapv2`, that will cause this iteration to not call the correct child class. If we use the base class `JetMap::Iter`, it will always be applicable since it is a requirement that the `vn` classes inherit from the base class. This also applies to the other instances of this

2022-12-08 15:04 UTC, antoniocosilva commented on offline/packages/ResonanceJetTagging/BuildResonanceJetTaggingTree.cc
> +    for (JetMapv1::Iter iter = m_taggedJetMap->begin(); iter != m_taggedJetMap->end(); ++iter)
Oh I see. I will change this and move BuildResonanceJetTaggingTree to the analysis repository. Thanks!

2022-12-08 18:53 UTC, osbornjd approved these changes

2022-12-08 18:56 UTC, merged