Fill match tables
sPHENIX-Collaboration/coresoftware pull request #1854
Opened 2023-03-03 03:13 UTC by david-stewart

[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)
Biggest result is addition of g4eval/FillTruthRecoMatchMap.{h,cc} which take the EmbRecoMatchContainer data
and fill PHG4ParticleSvxMap and PHG4PArticleSvtxMap nodes (named PHG4ParticleToRecoMap and RecoToPHG4ParticleMap, respectively) on the node tree.

Also of note, this changes the structure of TrkrTruthTrackContainer to store the TrkrTruthTraacks in a std::map instead of a std::vector. This is in anticipation of work adding nodes to the TrkrTruthTracks from the INTT and MVTX, as it became clear that the continued work around algorithmically in adding the tracks in three different modules just made the vector the wrong structure. I don't *think* that this would influence anybodies existing code/files/trees except possibly @jizhongling 

Note, the matching in the new nodes looks something like this (for embedded pions):
 ```--BEGIN-- Contents of PHG4ParticleToRecoMap:
    {  1 -> {  1.48 ->  2 },
         -> { 34.48 -> 12 }}
    {  2 -> { 31.48 ->  5 }}
...
    { 20 -> {  2.83 -> 33 }}
 --END-- Contents of SvtxPHG4ParticleMap:```
Where above 1, 2, ... 20 are the g4track id's, the floats are the matching parameters. In the existing PHG4ParticleToRecoMap nodes they just use integers that indicate the number of matched clusters. Here, they indicate the number of matched clusters + (total number of clusters in the g4track)/100. I.e. the `34.48` weighting means that the g4track (id 1) had 48 clusters, and 34 of them matched with the reco track (id 12).

Also as seen, the converter blindly fills *all* matches in the EmbRecoMatchContainer, even the match to track 2 which had only a single matching cluster. Which matches are made in that container are a function of parameters in the TruthRecoTrackMatching module set by the user.

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)

2023-03-03 18:53 UTC, david-stewart commented
I looked at the output of the output that from Valgrind claims that it is unstable, and it wasn't clear to me what the complaint was.

On the other hand, I also just got an email stating "[Build Status](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/sPHENIX_CoreSoftware_PullRequest/4691/) [builds and tests overall are SUCCESS](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/sPHENIX_CoreSoftware_PullRequest/4691/)." 

So, pushing this to "ready for review", but also happy to update the code to address the instability with further expert direction/advice.

2023-03-03 18:53 UTC, david-stewart commented
I looked at the output of the output that from Valgrind claims that it is unstable, and it wasn't clear to me what the complaint was.

On the other hand, I also just got an email stating "[Build Status](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/sPHENIX_CoreSoftware_PullRequest/4691/) [builds and tests overall are SUCCESS](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/sPHENIX_CoreSoftware_PullRequest/4691/)." 

So, pushing this to "ready for review", but also happy to update the code to address the instability with further expert direction/advice.

2023-03-03 18:57 UTC, blackcathj commented
> I looked at the output of the output that from Valgrind claims that it is unstable, and it wasn't clear to me what the complaint was.
> 
> On the other hand, I also just got an email stating "[Build Status](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/sPHENIX_CoreSoftware_PullRequest/4691/) [builds and tests overall are SUCCESS](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/sPHENIX_CoreSoftware_PullRequest/4691/)."
> 
> So, pushing this to "ready for review", but also happy to update the code to address the instability with further expert direction/advice.

Don't worry about it. 

Longer answer: we were setup in the way to allow valgrind to have max-1 error but still passes the CI check job. This seems to be a G4 related memory leak comes and goes, but not related to you at all. The build would be marked as "unstable" to remind us @pinkenburg to try to mask it :) : 
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-valgrind-pipeline/2649/valgrindResult/pid=84920,0x17888a/

2023-03-03 19:02 UTC, osbornjd requested changes

2023-03-03 19:02 UTC, osbornjd commented on offline/packages/trackbase/Makefile.am
> +	-lphg4hit
We may need to setup a new package for this development

2023-03-03 19:02 UTC, osbornjd commented on offline/packages/trackbase/TrkrTruthTrackContainerv1.cc
> +using std::set;
In general, although it is annoying, I suggest not using the `using` keyword for aliasing namespaces.  Although the likelihood for issues in this case is low, its a good habit to get into so that you are always 100% sure which function/operator/whatever you are calling

2023-03-03 19:02 UTC, osbornjd commented on simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
> +  f_out.open("PHG4TpcElectronDrift_out.txt");
What is this for in the electron drift?

2023-03-03 19:02 UTC, osbornjd commented on simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
> +  f_out.open("PHG4TpcElectronDrift_out.txt");
or maybe a different question, what is the purpose of the electron drift writing this text file?

2023-03-03 19:06 UTC, david-stewart commented on simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
> +  f_out.open("PHG4TpcElectronDrift_out.txt");
good catch -- this is legacy code from a study that I was doing, and should not have sneaked into this commit. I will remove it

2023-03-03 19:18 UTC, david-stewart commented on offline/packages/trackbase/Makefile.am
> +	-lphg4hit
this is good feedback. I was a bit nervous about this and asked Chris Pinkenburg if this would hurt the dependencies and he said that it should be ok because lphg4hit is built first.

However, I can also easily (if somewhat less gracefully) work around not having it.
Full story:
The TrkrTruthTrackContainer is really only for tracks with reconstructed hits, and probably should be filled with a bunch of "Tracks" from the PHG4TruthInfoContainer which aren't really tracks at all. For the modules that I am coding, it is most convenient, then, to just call the container for a given track in ElectrongDrift, or INTT, or MVTX, when it is actually needed to make the track, and then the TrkrTruthTrackContainer can just make the track on demand if it doesn't already exist. That is what the function TrkrTruthTrackContainer::getTrack(int trackid, PHG4TruthInfoContainer*) does.

That being said, I suspect that function call will only be used in those three above files. So if it is best to move it outside of the container and just have that code repeated locally in those 3 (more later?) places, in order to remove the lphg4hit dependency I will

2023-03-03 19:22 UTC, osbornjd commented on offline/packages/trackbase/Makefile.am
> +	-lphg4hit
In principle it isn't a dependency issue, it's an issue of introducing some simulation related thing into the reconstruction package which we want to be able to use on only reconstructed data. The hit generation for the MVTX, INTT, and TPC (electron drift) are all in the g4simulation area, which keeps them separate. I'm wondering if we led you astray at the beginning and that this development should be happening here

2023-03-03 19:23 UTC, david-stewart commented on offline/packages/trackbase/TrkrTruthTrackContainerv1.cc
> +using std::set;
I think that that is fair. My only quibble is that this is within a given implementation file (*.cc) instead of a header file (*.h), and are only for specific objects and not entire namespaces. I fluctuate similarly with the naming of local member variables as something annoyingly long like "m_TrkrTruthTrackContainer" vs "m_tracks" vs just "tracks" where there seems to be a legitimate tradeoff in clarity between lowering the cognitive overhead of messy names but also losing details...

2023-03-03 19:30 UTC, david-stewart commented on offline/packages/trackbase/Makefile.am
> +	-lphg4hit
Ah, I see. By that logic, it makes sense to put TrkrTruthTrack, TrkrTruthTrackContainer, EmbRecoMatch and EmbRecoMatchContainer somewhere in g4simulation. It would be easiest to put it locally under one of the existing g4simulation/g4\* directories, but it may be most logical to put it it's own g4simluation/g4-new-name directory.

Happy to do any of the above

2023-03-03 19:39 UTC, sPHENIX-GitHub-l commented
Yes, putting it in its own directory would be the preferred solution. That would make it similar to g4eval.

Tony
________________________________
From: sPHENIX-GitHub-l ***@***.***> on behalf of david-stewart ***@***.***>
Sent: Friday, March 3, 2023 2:30 PM
To: sPHENIX-Collaboration/coresoftware ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [Sphenix-github-l] [sPHENIX-Collaboration/coresoftware] Fill match tables (PR #1854)


@david-stewart commented on this pull request.

________________________________

In offline/packages/trackbase/Makefile.am<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1854*discussion_r1124925448__;Iw!!PhOWcWs!xxa4nExQ4W6T9y-vTFu5p-_nSrM4nJ7sB-0k92bFCMQqzJx5BE5rPoXRAw5EdOwaAukrBg8wSeXLebAuqS_fVQgN$>:

> @@ -281,7 +281,8 @@ libtrack_io_la_LIBADD = \
   -lphool \
   -lActsCore \
   -lActsPluginTGeo \
-  -lffamodules
+  -lffamodules \
+       -lphg4hit


Ah, I see. By that logic, it makes sense to put TrkrTruthTrack, TrkrTruthTrackContainer, EmbRecoMatch and EmbRecoMatchContainer somewhere in g4simulation. It would be easiest to put it locally under one of the existing g4simulation/g4* directories, but it may be most logical to put it it's own g4simluation/g4-new-name directory.

Happy to do any of the above

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1854*discussion_r1124925448__;Iw!!PhOWcWs!xxa4nExQ4W6T9y-vTFu5p-_nSrM4nJ7sB-0k92bFCMQqzJx5BE5rPoXRAw5EdOwaAukrBg8wSeXLebAuqS_fVQgN$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AEALMH2WXC7CWV4BOA7CX6LW2JBGRANCNFSM6AAAAAAVOC4FPU__;!!PhOWcWs!xxa4nExQ4W6T9y-vTFu5p-_nSrM4nJ7sB-0k92bFCMQqzJx5BE5rPoXRAw5EdOwaAukrBg8wSeXLebAuqQasOxDv$>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-03-03 19:41 UTC, osbornjd commented on offline/packages/trackbase/Makefile.am
> +	-lphg4hit
I would agree with Tony, we should put this in a new package that would be analogous to the g4eval package

2023-03-03 19:44 UTC, david-stewart commented on offline/packages/trackbase/Makefile.am
> +	-lphg4hit
ok -- done! (after I ask lots of questions, lol...)
Proposed package name:: `g4tracks` and pull from there

2023-03-03 19:45 UTC, osbornjd commented on offline/packages/trackbase/Makefile.am
> +	-lphg4hit
Either that or g4tracking sounds good to me, I think they both convey the same thing

2023-03-03 19:46 UTC, osbornjd commented on offline/packages/trackbase/TrkrTruthTrackContainerv1.cc
> +using std::set;
Sure, it's not the end of the world here. Just a word of caution that I myself have had to dig out a bug where I was using several namespaces and both had the same function defined and my code was using one and not the other inadvertently...

2023-03-08 00:33 UTC, david-stewart commented
As we discussed, @osbornjd  and @adfrawley, I have moved the modules to `g4simulation/g4tracking`

2023-03-08 18:30 UTC, osbornjd approved these changes
Looks good, I just made one small comment regarding a README

2023-03-08 18:30 UTC, osbornjd commented on simulation/g4simulation/g4tpc/readme.md
> +This job run from this macro branch:
I'm assuming this was put here by accident?

2023-03-09 13:50 UTC, osbornjd commented
Jenkins already approved, no need to run again after removing a markdown file

2023-03-09 13:50 UTC, merged