Fix the Magnetic Field in the KFParticle
sPHENIX-Collaboration/coresoftware pull request #1987
Opened 2023-04-27 18:42 UTC by MYOMAO

[comment]: <> (Please tell us something about this pull request)

After the studies on KS0 reconstruction performance, we found that the magnetic field used in KFParticle for track propagation is incorrect. The magnetic field is in kilo Gauss instead of Telsa. Also positive magnetic field indicate the +z direction, which is actually where the magnetic field of sPHENIX. Hence, we change the magnetic field from -1.4 -> 14 to represent the B field of 1.4 T in the +z direction for sPHENIX.  

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)

2023-04-27 18:48 UTC, MYOMAO commented on offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
> +  KFParticle::SetField(14.0);
I will have a look at that.

2023-04-27 18:56 UTC, osbornjd commented on offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
> +  KFParticle::SetField(14.0);
[Here](https://github.com/sPHENIX-Collaboration/coresoftware/blob/b68653a3c6eb141d226e86d4e5dc24439c34221f/offline/packages/trackreco/MakeActsGeometry.cc#L478-L483) is where we get the fieldmap. We could get that root file, open it up, and then  get the bz value at (0,0,0).

2023-04-27 19:17 UTC, MYOMAO commented on offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
> +  KFParticle::SetField(14.0);
It appears that is in T not in kG @osbornjd @blackcathj. We need to convert the unit.

2023-05-03 03:33 UTC, blackcathj requested changes
Loading field map in `KFParticle_eventReconstruction::createDecay()` is problematic: 

1. This function is called every event and loading Bfield each time is very inefficient. Please move it to be initialized once. 
2. Please also make the field file name settable via Fun4All macro

A solution is to moving this block of field map reading to `KFParticle_sPHENIX` `InitRun()`, which then set single Bz field value to `KFParticle_eventReconstruction` via a setter like `KFParticle_eventReconstruction::setBz(double B_Tesla)`

2023-05-03 13:47 UTC, pinkenburg commented
We should move to using the cdb to get the fieldmap like in 
simulation/g4simulation/g4main/PHG4Reco.cc. This snippet will fall back to CALIBRATIONSROOT if the CDB cannot locate the file:

#include <ffamodules/CDBInterface.h>

char *calibrationsroot = getenv("CALIBRATIONROOT");
  std::string m_magField = "sphenix3dtrackingmapxyz.root";
  if (calibrationsroot != nullptr)
  {
	  m_magField = std::string(calibrationsroot) + std::string("/Field/Map/") + m_magField;
  }
std::string url = CDBInterface::instance()->getUrl("FIELDMAPBIG", m_magField);

2023-05-03 13:51 UTC, osbornjd commented
Which fieldmaps are in the CDB? We have several, the big one is way too large for the purposes of tracking so for memory usage purposes we should use the tracking volume only map. Are all of the maps that are in the calibrations repo, i.e. in `$CALIBRATIONROOT/FieldMap/` also in the CDB?

2023-05-03 13:55 UTC, pinkenburg commented
Sorry my bad - we need to give it another name "FIELDMAPTRACKING". I'll add it to the cdb and the above construct will read it from CALIBRATIONSROOT until this is done

2023-05-03 15:42 UTC, MYOMAO commented
OK I will implement the setter and put my codes there.

2023-05-04 11:52 UTC, osbornjd requested changes
Can you also implement Chris' suggestion to call from the CDB if the file exists there, and to otherwise revert to the calibrations repo:

```
#include <ffamodules/CDBInterface.h>
...
char *calibrationsroot = getenv("CALIBRATIONROOT");
std::string m_magField = "sphenix3dtrackingmapxyz.root";

std::string url = CDBInterface::instance()->getUrl("FIELDMAPBIG", m_magField);

if (calibrationsroot != nullptr)
{
m_magField = std::string(calibrationsroot) + std::string("/Field/Map/") + m_magField;
}
```

2023-05-04 13:37 UTC, pinkenburg commented
I looked at the cppcheck failure and saw the code does not follow our conventions about include files which are really important
https://wiki.sphenix.bnl.gov/index.php/Codingconventions

2023-05-04 13:52 UTC, pinkenburg commented
> Can you also implement Chris' suggestion to call from the CDB if the file exists there, and to otherwise revert to the calibrations repo:
> 
> ```
> #include <ffamodules/CDBInterface.h>
> ...
> char *calibrationsroot = getenv("CALIBRATIONROOT");
> std::string m_magField = "sphenix3dtrackingmapxyz.root";
> 
> std::string url = CDBInterface::instance()->getUrl("FIELDMAPBIG", m_magField);
> 
> if (calibrationsroot != nullptr)
> {
> m_magField = std::string(calibrationsroot) + std::string("/Field/Map/") + m_magField;
> }
> ```

In the meantime I added the tracking fieldmap to our cdb, please use 
std::string url = CDBInterface::instance()->getUrl("FIELDMAPTRACKING", m_magField);
to fetch it. Otherwise you load our big map

2023-05-04 20:52 UTC, MYOMAO commented
Somehow I messed up the rebase and produced many commits here...

2023-05-04 21:15 UTC, closed without merging