New Fix on KFParticle Magnetic Field using the Official Map
sPHENIX-Collaboration/coresoftware pull request #1999
Opened 2023-05-04 21:45 UTC by MYOMAO

We identified that unit and the direction are wrong in the official KFParticle codes. We made a pull request [#1987 ](url) before to fix this error. Somehow we did not do the commit correctly and have to close the pull request. Now we make sure we do all github commands correctly and open a fresh pull request. In this pull request, we take the suggestions from Chris and Joe to use the official full file name from the CDB and load the magnetic field map for KFParticle.  

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)

2023-05-04 23:49 UTC, blackcathj commented
Last report was github connectivity issue. Restarting

2023-05-05 00:57 UTC, osbornjd requested changes

2023-05-05 00:57 UTC, osbornjd commented on offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
> +#include "TFile.h"                    // for reading the field map file
You need to use <> for these ROOT includes and not "" as Chris mentioned

2023-05-05 00:57 UTC, osbornjd commented on offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
> +    m_magField = std::string(calibrationsroot) + std::string("/Field/Map/") + m_magField;
I gave you bad information, I tested this locally just now and it works
```
 char *calibrationsroot = getenv("CALIBRATIONROOT");
m_magField = "sphenix3dtrackingmapxyz.root";
      
 if (calibrationsroot != nullptr)
   {
    m_magField = std::string(calibrationsroot) + std::string("/Field/Map/") + m_magField;
  }
      
      m_magField = CDBInterface::instance()->getUrl("FIELDMAPTRACKING", m_magField);
```
Please use this and not what you currently have. Sorry for my mistake

2023-05-05 04:56 UTC, MYOMAO commented
OK I am fixing it now and resubmit my commit. Thank you very much!

2023-05-06 22:28 UTC, MYOMAO commented
Again, I messed up this pull request. I will again delete this one and create a new pull request.

2023-05-06 22:28 UTC, closed without merging