first version of MVTX unpacker
sPHENIX-Collaboration/coresoftware pull request #2002
Opened 2023-05-05 17:35 UTC by KvapilJ

first version of MVTX data unpacker, currently no online_distributions calls are implemented since there is no decoder, there is hardcoded fill for the DST: 1 hitsetkey with 10 hitsets

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

first version of MVTX data unpacker

## TODOs (if applicable)

implement actual online_distributions calls once we have decoder

## Links to other PRs in macros and calibration repositories (if applicable)

2023-05-05 21:16 UTC, pinkenburg requested changes
Please follow our conventions for include files:
https://wiki.sphenix.bnl.gov/index.php/Codingconventions#Include_Files
this is important and will bite us if this is being ignored

2023-05-05 21:27 UTC, KvapilJ commented
not sure that was the requested change...changed <> to ""

2023-05-05 21:48 UTC, pinkenburg commented
https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html#Directory-Options

> not sure that was the requested change...changed <> to ""
There is a subtle but important difference between #include <> and #include ""
https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html#Directory-Options

-->1.For the quote form of the include directive, the directory of the current file is searched first. 

We use this feature to be able to put our modified include files in our own installation area ahead of the generally installed ones even if those includes are included by another include. Takes a while to wrap one's head around but it does the trick. If we don't follow our include file convention, this might break and you might deal with shared libraries which were build using contradicting include files which is endless fun (completely unpredictable and weird results)

2023-05-06 13:06 UTC, pinkenburg approved these changes

2023-05-06 13:06 UTC, merged