Updates to the jet reconstruction:
sPHENIX-Collaboration/coresoftware pull request #2143
Opened 2023-07-14 19:44 UTC by david-stewart

Can fill JetContainer(s) instead of JetMap(s)
  - requires that Jetv2 be used - Jetv2 internally has vector<float> that contain all additional data (jet area, zg, etc...) - This additiona data is indexed and access from the JetContainer
  - the Jetv2 are stored in a TClonesArray, instead of std::map<unsigned int, Jet*>

I will present this first to the Jet Substructure group before making the pull request. There is still a lot of work to come, but this is a good, working point, to stop and get feedback for the downstream users and other experts.

[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
       Updates to the FastJetAlgo, JetAlgo, and JetReco to use a new JetContainer in place of a JetMap.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)
- Use of TClonesArray(s) will help with execution instead of the std::map in use in JetMap classes
- Internal to each Jetv2 there is:
    -  vector<float> for the properties instead of a map<Jet::PROPERTY,float> in Jetv1
    - vector<pair<Jet::SRC,unsigned int>> in place of std::multimap<Jet::SRC, unsgiend int> in Jetv1

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)

2023-07-20 22:26 UTC, osbornjd commented
This is my fault I was tooling around with some things in the package list. Push an empty commit to retrigger Jenkins

2023-08-31 13:52 UTC, david-stewart commented
Hi @pinkenburg , I have tried to address your concerns and remove the vestigal code that had been left over from the sorting functionality. Is there anything more that you will to be vetted from your side before merging this? Thanks, Dave

2023-08-31 14:13 UTC, pinkenburg commented on offline/packages/jetbase/Jetv2.h
please order the methods/data members so there is one public and one private section. Currently this has multiple private/public declarations. This is legal C++ but this makes this hard to understand

2023-08-31 14:14 UTC, pinkenburg commented
I gave the feedback in MM:
https://chat.sdcc.bnl.gov/sphenix/channels/jet-structure-tg

The include file ordering is mostly not correct:
https://wiki.sphenix.bnl.gov/index.php/Codingconventions#Include_Files
using the wrong ordering in include files will create problems if you have your own installation area with modified files

Then in Jetv2.h :
mutable bool _is_sorted { false }; // if the _comp_ids (component ids) are sorted
I thought sorting is done in a helper class. We shouldn't carry flags into our DSTs

The Jetv2.h is done but the proper include file ordering (and use of "" vs <>) is not.

2023-08-31 18:28 UTC, david-stewart commented
ok sounds good. I didn't mention in my comment, but I had fixed the include statements with the previous commit. They all match the documentation that you sent.

I have now also rearranged the private/public methods with this commit

2023-08-31 19:08 UTC, pinkenburg commented on offline/packages/jetbase/ClusterJetInput.h
Why does this include exist?

2023-08-31 19:09 UTC, pinkenburg commented on offline/packages/jetbase/ClusterJetInput.cc
Why does this file exist?

2023-08-31 19:10 UTC, pinkenburg commented on offline/packages/jetbase/FastJetAlgo.h
use #include <fastjet/...>

2023-08-31 19:41 UTC, pinkenburg requested changes
clang-format -style=file -i 
needs to be applied to all modified sources.

2023-08-31 19:41 UTC, pinkenburg commented on offline/packages/jetbase/FastJetOptions.cc
leave empty lines between groups of include
run clang-format -style=file -i

2023-08-31 19:41 UTC, pinkenburg commented on offline/packages/jetbase/FastJetOptions.h
Please do not use "_" as variable name, this will confuse people reading this code

2023-08-31 19:41 UTC, pinkenburg commented on offline/packages/jetbase/Jet.h
why is mv1 and mv2 which are JetV dependent implemented in the base class?
they have the same signatures (string, ostream), and presumably do the same, why not a generic mv and implement the real method in the versioned class?

2023-08-31 19:41 UTC, pinkenburg commented on offline/packages/jetbase/JetContainer.h
use climits instead of limits.h

2023-08-31 19:41 UTC, pinkenburg commented on offline/packages/jetbase/JetContainerv1.cc
use int i = 0 instead of int i {0}

2023-08-31 19:41 UTC, pinkenburg commented on offline/packages/jetbase/TowerJetInput.h
move calobase include ahead of iostream

2023-08-31 23:21 UTC, pinkenburg commented
just noticed, it seems to affect the e- jet qa:
[QA-calorimetric-jet for e- at p_T=4GeV](https://nbviewer.jupyter.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-calo-single-qa-5107-e-_pT4_Sum14/QA-calorimetric-jet.ipynb) : combined Chi2/nDoF = 332.222 / 42, and combined p-Value = 8.6305e-47
All other PR's are fine, so it is likely related to this one

2023-09-01 18:15 UTC, david-stewart commented on offline/packages/jetbase/FastJetOptions.cc
done

2023-09-01 19:06 UTC, david-stewart commented on offline/packages/jetbase/Jet.h
I have updated them to a single depmsg which uses two static strings for the differentiation between version.

2023-09-01 19:06 UTC, david-stewart commented on offline/packages/jetbase/JetContainer.h
done

2023-09-01 19:13 UTC, david-stewart commented on offline/packages/jetbase/JetContainerv1.cc
ok, changed in all places in this file.
But why? int i{0} is correct, and at least as far as the venerable and opinionated Bjarne Stroustrup seems to say, it is probably preferable because is it acceptable in _all_ contexts, see for instance: https://www.stroustrup.com/list-issues-2.pdf

2023-09-01 19:14 UTC, david-stewart commented on offline/packages/jetbase/TowerJetInput.h
done

2023-09-01 20:08 UTC, david-stewart commented on offline/packages/jetbase/FastJetAlgo.cc
ok, think I got them all

2023-09-01 20:12 UTC, david-stewart commented on offline/packages/jetbase/ClusterJetInput.h
Not sure. Git blame says that all I did was add include guards in the *.h file; otherwise it all predates me. Should I remove it?

2023-09-01 20:18 UTC, david-stewart commented on offline/packages/jetbase/FastJetAlgo.h
done

2023-09-01 20:18 UTC, david-stewart commented on offline/packages/jetbase/FastJetOptions.h
ok, done

2023-09-04 23:17 UTC, pinkenburg commented
The calorimeter jet QA for e- is very different from the reference, it looks like some histos aren't filled with the code in this PR. This needs to be understood and fixed

2023-09-13 12:26 UTC, osbornjd commented
@david-stewart The QA code can be found [here](https://github.com/sPHENIX-Collaboration/coresoftware/blob/master/offline/QA/modules/QAG4SimulationCalorimeter.cc). In that directory you can also see the other QA modules (e.g. tracking etc.). You can compile these locally and run them in your macro by setting the flag `Enable::QA=true`, which will dump all of the information from these modules into a TFile that you can look through to identify what is going haywire.

2023-09-29 18:11 UTC, david-stewart commented
Hey @pinkenburg and @osbornjd ,
I started looking at this yesterday. There is a failure somewhere, presumably in the QA, where things die because a Jetv1 is getting called with a method defined only for Jetv2. This is pretty weird. I haven't found the location yet, but hopefully will be an easy fix.

2023-09-29 18:16 UTC, osbornjd commented
All the QA modules are under this area:
https://github.com/sPHENIX-Collaboration/coresoftware/tree/master/offline/QA/modules
So you can check there for issues

2023-09-30 16:10 UTC, pinkenburg commented
The calorimetric jet for e- still shows a drastic change because of empty historgrams (I assume). I converted the PR to draft so it doesn't get merged accidentally

2023-11-02 17:24 UTC, osbornjd commented
I restarted your build manually after Jenkins crashed yesterday and it looks like there are still some nontrivial changes to one of the calo QAs, these should be checked if they are understood
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-calo-single-qa/5415/

2023-11-02 17:30 UTC, david-stewart commented
> I restarted your build manually after Jenkins crashed yesterday and it looks like there are still some nontrivial changes to one of the calo QAs, these should be checked if they are understood https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-calo-single-qa/5415/

Thanks -- I am running things manually and trying to pin down the differences, using the QA macro indicated by @blackcathj. When running a single event, the JetMap's have identical output, but something is happening with multiple events. Still trying to understand why.

2023-11-05 13:46 UTC, pinkenburg commented
It now passes the calorimeter jet qa for e- without modifications in jenkins, good to go

2023-11-05 13:46 UTC, merged