Added pedestal RMS and ZS RMS histograms
sPHENIX-Collaboration/coresoftware pull request #2819
Opened 2024-06-05 14:31 UTC by kr2580

[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

Added pedestal RMS and zero-suppressed RMS histograms in iphi and ieta.

2024-06-06 03:17 UTC, osbornjd requested changes

2024-06-06 03:17 UTC, osbornjd commented on offline/QA/Calorimeters/CaloValid.cc
> +#include <calobase/TowerInfov2.h>
We should only include the base class, the versioned classes should never need to be included in analysis modules. If they are needed then something has gone wrong

2024-06-06 03:17 UTC, osbornjd commented on offline/QA/Calorimeters/CaloValid.cc
> +  OutputNtupleFile = new TFile(OutputFileName.c_str(),"RECREATE");
You should not use a new file, you should use the histomanager will deal with all the histogram memory management for you like is done in `createHistos`

2024-06-06 03:17 UTC, osbornjd commented on offline/QA/Calorimeters/CaloValid.cc
> +    sprintf(hname,"h_cemc_channel_pedestal_%d",channel);
see `createHistos()` to use boost instead of sprintf

2024-06-06 03:17 UTC, osbornjd commented on offline/QA/Calorimeters/CaloValid.cc
> +  QAHistManagerDef::saveQARootFile(OutputFileName);
This is not needed, this should be called in your macro. The production needs to work this way so that file names can be specified as they already are in the production scripts

2024-06-06 03:17 UTC, osbornjd commented on offline/QA/Calorimeters/CaloValid.h
> +  TH1F* h_ihcal_channel_pedestal[32*48];
These should not be needed to be owned by the CaloValid module if they are properly registered with the QAUtil HistoManager, which will do the memory management for you

2024-06-06 22:16 UTC, kr2580 commented on offline/QA/Calorimeters/CaloValid.h
> +  TH1F* h_ihcal_channel_pedestal[32*48];
These are temporary histograms, should I still use the histogram manager? I do not want them saved to the output file

2024-06-07 01:35 UTC, pinkenburg commented on offline/QA/Calorimeters/CaloValid.h
> +  TH1F* h_ihcal_channel_pedestal[32*48];
If you don't register the histograms with the qa, they won't be saved. Means don't use the histo manager for those

2024-06-07 15:28 UTC, kr2580 commented on offline/QA/Calorimeters/CaloValid.h
> +  TH1F* h_ihcal_channel_pedestal[32*48];
Just to make sure, I can leave these histograms like this?

2024-06-07 15:39 UTC, pinkenburg commented
sorry - pushed the wrong button. Yes the histos are fine. I just modified the include file - we try to use base class pointers (TH1*, TH2*), the type is set when the histogram is created with TH2 *h2 = new TH2F.. This allows us to change easily the type if needed (e.g. going from floats to doubles TH2F to TH2D) in a single place - just like out versioned classes

2024-06-08 03:53 UTC, merged