Adding the photon kinematics for the EMCal clusters QA type plots
sPHENIX-Collaboration/coresoftware pull request #3175
Opened 2024-10-08 14:59 UTC by aahanab

[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)
Adding the photon kinematics plots (eta, phi, energy and chi squared) for the EMCal clusters.
[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)

2024-10-09 05:32 UTC, ruse-traveler requested changes
This is very nice to see! Thank you for the work on this!!

In general, things are in very good shape, but there's a some work to do to get it working within the QA environment. I've written out all of my suggestions in the review comments!

The only other thing is to make sure to add your `.h` and `.cc` files to the Makefile!

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.h
> +class PHCompositeNode;
We'll need to do a forward declaration for the hist manager...
```suggestion
class Fun4AllHistoManager;
class PHCompositeNode;
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.h
> +
We'll need the hist manager to collect the output histograms...
```suggestion

// hist manager
Fun4AllHistoManager* manager;
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  PHTFileServer::get().open(outfilename, "RECREATE");
Instead of sending the histograms to a specific output file, we'll pipe them into the QA hist manager which handles all of that downstream.
```suggestion
manager = QAHistManagerDef::getHistoManager();
if (!manager)
{
  std::cerr << PHWHERE << "PANIC: couldn't grab histogram manager!" << std::endl;
  assert(manager);
}
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +
We'll also need a few standard headers as well...
```suggestion

// c++ includes
#include <algorithm>
#include <cassert>
#include <iostream>
#include <vector>

```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +
The following suggestion is for making sure the histogram names conform to the same pattern that most of the other modules follow: `h_<module name>_<what it is>_<additional tags>`. The first chunk just makes sure that the module name is all lower-case, and the second chunk systematically makes sure each histogram has the same prefix and suffix.

```suggestion

// make sure module name is lower case
std::string smallModuleName = modulename;
std::transform(
  smallModuleName.begin(),
  smallModuleName.end(),
  smallModuleName.begin(),
  ::tolower);

// construct histogram names
std::vector<std::string> vecHistNames = {
  "emcal_cluster_chi2",
  "emcal_cluster_energy",
  "emcal_cluster_eta_phi",
  "emcal_cluster_eta",
  "emcal_cluster_phi"};
for (auto& histName : vecHistName)
{
  histName.insert(0, "h_" + smallModuleName + "_");
  if (!histtag.empty())
  {
    histName.append("_" + histtag);
  }
}

```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  h_emcal_cluster_chi2 = new TH1D("h_emcal_cluster_chi2", "h_emcal_cluster_chi2", 30, 0, 150); //1000,0,5e6
Then we can use the vector of histogram names from above to name each one.
```suggestion
  h_emcal_cluster_chi2 = new TH1D(vecHistName[0].data(), "h_emcal_cluster_chi2", 30, 0, 150); //1000,0,5e6
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  h_emcal_cluster_energy = new TH1D("h_emcal_cluster_energy", "h_emcal_cluster_energy", 100, 0, 10);
```suggestion
  h_emcal_cluster_energy = new TH1D(vecHistName[1].data(), "h_emcal_cluster_energy", 100, 0, 10);
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  h_emcal_cluster_eta_phi = new TH2F("h_emcal_cluster_eta_phi", "h_emcal_cluster_eta_phi", 140, -1.2, 1.2, 64, -M_PI, M_PI);
```suggestion
  h_emcal_cluster_eta_phi = new TH2F(vecHistName[2].data(), "h_emcal_cluster_eta_phi", 140, -1.2, 1.2, 64, -M_PI, M_PI);
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  h_emcal_cluster_eta = new TH1D("h_emcal_cluster_eta", "Eta Distribution", 140, -1.2, 1.2);
```suggestion
  h_emcal_cluster_eta = new TH1D(vecHistName[3].data(), "Eta Distribution", 140, -1.2, 1.2);
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  h_emcal_cluster_phi = new TH1D("h_emcal_cluster_phi", "Phi Distribution", 64, -M_PI, M_PI);
```suggestion
  h_emcal_cluster_phi = new TH1D(vecHistName[4].data(), "Phi Distribution", 64, -M_PI, M_PI);
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  std::cout << "photonjetskinematics::Init(PHCompositeNode *topNode) Initializing" << std::endl;
```suggestion
  if (Verbosity() > 1) std::cout << "photonjetskinematics::Init(PHCompositeNode *topNode) Initializing" << std::endl;
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  std::cout << "photonjetskinematics::InitRun(PHCompositeNode *topNode) Initializing for Run XXX" << std::endl;
```suggestion
  if (Verbosity() > 1) std::cout << "photonjetskinematics::InitRun(PHCompositeNode *topNode) Initializing for Run XXX" << std::endl;
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  RawClusterContainer* clusterContainer = findNode::getClass<RawClusterContainer>(topNode, "CLUSTERINFO_CEMC");
```suggestion
  RawClusterContainer* clusterContainer = findNode::getClass<RawClusterContainer>(topNode, inputnode);
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  std::cout << "photonjetskinematics::EndRun(const int runnumber) Ending Run for Run " << runnumber << std::endl;
```suggestion
  if (Verbosity() > 1) std::cout << "photonjetskinematics::EndRun(const int runnumber) Ending Run for Run " << runnumber << std::endl;
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +
We'll need to add a chunk of code here to filter out events which don't have the trigger we're interested in if we're applying a trigger selection.
```suggestion
// if needed, check if trigger fired
if (doTrgSelect)
{
  bool hasTrigger = JetQADefs::DidTriggerFire(trgToSelect, topNode);
  if (!hasTrigger)
  {
    return Fun4AllCodes::EVENT_OK;
  }
}

```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  std::cout << "photonjetskinematics::End - Output to " << outfilename << std::endl;
```suggestion
  if (Verbosity() > 1) std::cout << "photonjetskinematics::End - Output to " << outfilename << std::endl;
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  //outfile->cd("photonjetskinematics");
The manager will handle all histogram saving...
```suggestion
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  h_emcal_cluster_phi->Write("h_emcal_cluster_phi");  // Save 1D phi plot
Here we instead register the output histograms with the manager rather than save them to a particular file.
```suggestion
  manager->registerHisto(h_emcal_cluster_eta_phi);
  manager->registerHisto(h_emcal_cluster_energy);
  manager->registerHisto(h_emcal_cluster_chi2);
  manager->registerHisto(h_emcal_cluster_eta);  // Save 1D eta plot
  manager->registerHisto(h_emcal_cluster_phi);  // Save 1D phi plot
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  std::cout << "photonjetskinematics::End(PHCompositeNode *topNode) This is the End..." << std::endl;
```suggestion
  if (Verbosity() > 1) std::cout << "photonjetskinematics::End(PHCompositeNode *topNode) This is the End..." << std::endl;
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> + std::cout << "photonjetskinematics::Reset(PHCompositeNode *topNode) being Reset" << std::endl;
```suggestion
 if (Verbosity() > 1) std::cout << "photonjetskinematics::Reset(PHCompositeNode *topNode) being Reset" << std::endl;
```

2024-10-09 05:32 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  std::cout << "photonjetskinematics::Print(const std::string &what) const Printing info for " << what << std::endl;
```suggestion
  if (Verbosity() > 1) std::cout << "photonjetskinematics::Print(const std::string &what) const Printing info for " << what << std::endl;
```

2024-10-16 16:44 UTC, ruse-traveler approved these changes
Thanks for the changes!! For some reason I can't mark my previous suggestions as resolved, but I'm happy with this as-is!

The only other comment is a minor one about using `m_` prefixes, but I'll leave it up to you whether or not to implement it. (I can always implement it later in a subsequent editing pass.)

2024-10-16 16:44 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +photonjetskinematics::photonjetskinematics(const std::string &m_modulename, const std::string &m_inputnode) :
Apologies! I should've been more clear: the `m_` is for variables that are class members (e.g. the ones starting at line 75 of the .h file), and then the arguments here usually aren't prefixed by anything😅

2024-11-18 14:37 UTC, ruse-traveler approved these changes
Looks like Jenkins still isn't happy... The only issues are some clang-tidy warnings that aren't related to this PR and cpp-check, which is throwing an error about `manager` not being initialized in the constructor. Otherwise, all other checks are passed!

I've left a couple of comments in the code about how to fix the cpp-check issue...

2024-11-18 14:37 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.h
> + Fun4AllHistoManager* manager;
So (hopefully 🤞) this is the last issue: `manager` not being initialized in the constructor is throwing a warning on Jenkins... I'll add a comment where this needs to be added.

2024-11-18 14:37 UTC, ruse-traveler commented on offline/QA/Jet/photonjetskinematics.cc
> +  , doTrgSelect(false)
Here we'll need to initialize `manager`, so something like so:
```suggestion
  SubsysReco(m_modulename)
  , modulename(m_modulename)
  , inputnode(m_inputnode)
  , histtag("AllTrig")
  , trgToSelect(JetQADefs::GL1::MBDNSJet1)
  , doTrgSelect(false)
  , manager(nullptr)
```

2025-03-07 20:40 UTC, ruse-traveler commented
Hmmm... Interesting.... 🤔 

I just double-checked: this branch does compile on the Alma9 nodes, and the new module runs in a test F4A macro...

2025-03-18 15:49 UTC, pinkenburg commented
Please do not use github to merge your PR with the master, this just triggers a jenkins run and klogs up our system. Merge/rebase the master in your local fork - fix the problems and then push the PR when it's ready

2025-03-18 16:08 UTC, ruse-traveler commented
I could be misremembering, but I thought we discussed this last week: the previous Jenkins report indicated nothing wrong with the module here, I've confirmed that it compiles and runs natively under Alma9, and running cpp-check locally doesn't return any issues. And it was speculated that this could be due to Jenkins being interrupted (this could be the point I'm misremembered)...

Is there a way to run Jenkins that doesn't klog our system? For example, would an empty commit be better?

2025-03-18 16:13 UTC, pinkenburg commented
> I could be misremembering, but I thought we discussed this last week: the previous Jenkins report indicated nothing wrong with the module here, I've confirmed that it compiles and runs natively under Alma9, and running cpp-check locally doesn't return any issues. And it was speculated that this could be due to Jenkins being interrupted (this could be the point I'm misremembered)...
> 
> Is there a way to run Jenkins that doesn't klog our system? For example, would an empty commit be better?

that is a valid use, it is a way to trigger a jenkins run just like an empty commit. Sorry about the noise

2025-03-19 00:28 UTC, merged